services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql1
    ports:
      - 1433:1433
    env_file: ./.env
    environment:
      ACCEPT_EULA: Y
    volumes:
      - mssql-data:/var/opt/mssql

volumes:
  mssql-data:
